apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }} 
spec:
  storageClassName: {{ .Values.sc.name }} 
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.pvc.size }} 
  selector:
    matchLabels:
      name: {{ .Values.pv.name }} 